jonny5:
  joint_limits:
    base_joint: {min_deg: -45.0, max_deg: 45.0, velocity: 2.0}
    shoulder_joint: {min_deg: -60.0, max_deg: 55.0, velocity: 1.5}
    elbow_joint: {min_deg: -60.0, max_deg: 55.0, velocity: 1.5}
    wrist_yaw_joint: {min_deg: -45.0, max_deg: 45.0, velocity: 1.5}
    wrist_pitch_joint: {min_deg: -55.0, max_deg: 30.0, velocity: 1.5}
    wrist_roll_joint: {min_deg: -45.0, max_deg: 45.0, velocity: 1.5}
